spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1086547776276-970rldcpp246uivoen3q77rn9dulubi6.apps.googleusercontent.com
            client-secret: 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